#!/bin/bash

### MAIN SCRIPT LOCATIONS

## Menu/interface related scripts & assets
# Main menu
menu="scripts/menu.sh"
# Return to menu prompt after using a script
menuReturn="scripts/menuReturn.sh"
menuReturnSub="scripts/menuReturn.sh"
about="info/about.info"

## Automation scripts / tools / apps
# CPU > Performance mode
performance="scripts/performance.sh"
# Start up PulseAudio <> JACK bridged sinks
jackSinks="scripts/jacksinks.sh"
# Pulse sinks
pulseSinks="scripts/pulseSinks.sh"
# Start up v4l2loopback device to use OBS as camera
virtualCam="scripts/virtualcam.sh"
# Set resolution for drawing tablet
tabletFix="scripts/tabletfix.sh"
# Update grub config after changes
updateGrub="scripts/updategrub.sh"
# Change mouse cursor theme globally
cursorChange="scripts/cursorChange.sh"
# Remove orphaned packages via pacman
orphanRemoval="scripts/orphanRemoval.sh"

### MISC. VARIABLE LOCATIONS

## cursorChange variables

# Print theme name temp for cursorChange
themeName=./temp/themeName.info
# Get session of current user to log out for cursorChange
session=`loginctl session-status | head -n 1 | awk '{print $1}'`
